id: PD157D122
initial_creation_type: ocr
source_metadata:
  volumes:
    0a2835496ca84a45a0ba637c291bb2ba:
      base_file: v073.txt
      image_group_id: I1PD95918
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་ཉན་ཐོས་ཀྱི་ས།
      total_pages: 1125
      volume_number: 73
